name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      - run: npm run build

      - run: npx vsce package -o norrsken.vsix

      - uses: softprops/action-gh-release@v2
        with:
          files: norrsken.vsix

      - run: npx ovsx publish norrsken.vsix -p $OVSX_PAT
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}

      - run: npx vsce publish -p $VSCE_PUBLISHER_TOKEN
        env:
          VSCE_PUBLISHER_TOKEN: ${{ secrets.VSCE_PUBLISHER_TOKEN }}
